name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Ensure data directory exists
      run: |
        echo "Contents of dist:"
        ls -la dist/
        if [ ! -d "dist/data" ]; then
          echo "Creating data directory"
          mkdir -p dist/data
        fi
        if [ ! -f "dist/data/servers.json" ]; then
          echo "Copying servers.json"
          cp public/data/servers.json dist/data/
        fi
        echo "Final verification:"
        ls -la dist/data/
        echo "servers.json size: $(wc -c < dist/data/servers.json) bytes"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
